name: Validate algoku-frontend

on:
  workflow_call:

permissions:
  contents: read

jobs:
  ci:
    runs-on: ubuntu-latest
    env:
      VITE_ENVIRONMENT: local
      VITE_ALGOD_SERVER: http://localhost
      VITE_ALGOD_PORT: "4001"
      VITE_ALGOD_TOKEN: a
      VITE_ALGOD_NETWORK: localnet
      VITE_INDEXER_SERVER: http://localhost
      VITE_INDEXER_PORT: "8980"
      VITE_INDEXER_TOKEN: a
      VITE_KMD_SERVER: http://localhost
      VITE_KMD_PORT: "4002"
      VITE_KMD_TOKEN: a
      VITE_KMD_WALLET: unencrypted-default-wallet
      VITE_KMD_PASSWORD: ""

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: "./projects/algoku-frontend/package-lock.json"

      - name: Install dependencies
        working-directory: ./projects/algoku-frontend
        run: npm ci

      - name: Cache Playwright browsers
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: playwright-${{ runner.os }}-${{ hashFiles('projects/algoku-frontend/package-lock.json') }}

      - name: Install Playwright browsers and dependencies
        working-directory: ./projects/algoku-frontend
        run: npx playwright install --with-deps

      - name: Install just
        uses: extractions/setup-just@v2

      - name: Run CI
        run: just ci
