name: Release

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'docs/**'
      - '**.md'
      - '.vscode/**'
      - '.idea/**'

permissions:
  contents: read
  packages: read

jobs:
  changes:
    name: Detect changed paths
    runs-on: ubuntu-latest
    outputs:
      contracts: ${{ steps.filter.outputs.contracts }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            contracts:
              - 'algoku-contracts/**'

  algoku-contracts-validate:
    name: Run algoku-contracts validation
    needs: changes
    if: needs.changes.outputs.contracts == 'true'
    secrets: inherit
    uses: ./.github/workflows/algoku-contracts-ci.yaml

  algoku-contracts-release:
    name: Run algoku-contracts release
    needs: algoku-contracts-validate
    secrets: inherit
    uses: ./.github/workflows/algoku-contracts-cd.yaml

  algoku-frontend-validate:
    name: Run algoku-frontend validation
    secrets: inherit
    uses: ./.github/workflows/algoku-frontend-ci.yaml
